

class Challenge{
    constructor(name, level, skill, premise, choiceA, choiceB, choiceC, success, fail, avoid, keyType, key){
        this.name = name;
        this.level = level;
        this.skill = skill;
        this.premise = premise;
        this.choiceA = choiceA;
        this.choiceB = choiceB;
        this.choiceC = choiceC;
        this.success = success;
        this.fail = fail;
        this.avoid = avoid;
        this.keyType = keyType;
        this.key = key;
    }
}

var canyon = new Challenge("Canyon", 1, "Courage", "The path before you gives way to a steep canyon. The drop looks painful, though the gap is not so wide. Perhaps a well-executed leap might still land you on the other side.", "Leap to the other side.", "Find a way around.", "Use a Rope to get across", "You make the leap with no reservations and your courage holds true. You land safely on the other side and pat the dust from your body.", "You hesitate at the last second and slam against the lip of the otherside. You aren't concious when you land, but you wake to the intense throbbing of your entire body. You find a place where the canyon yields and climb to the other side.", "You leave the worn path and walk for what seems like miles until the canyon yields. You return to the path on the other side, exhausted by the effort.", rope, "With your rope and some debris found around you, you are able to grapple over to the other side with little trouble.");

var thornbush = new Challenge("Thornbush", 1, "Guile", "Sprawling over the worn path for what seems like miles is a dense bush of wicked thorns. Each tendril is thick like a branch, and it may be possible to slip gracefully between them, avoiding the thorns. But the pained screams of other trapped animals is a grim reminder of the consequences getting trapped.", "Manuever through the thorn bushes.", "Find a way around.", "Ignite the bushes with a Torch.", "You duck into the thorns and intensly focus on every inch of movement. Carefully, meticulously, you traverse the briar, and manage to squeeze out the other side without so much as a scratch.", "You begin your descent into the wicked plants. Every step you take leaves you with a nasty cut. The thorns dig into you a little more each time and the panic sets in. Your movements become labored and clumsy as you struggle to press through. You crawl out the other side, shaking from the pain of a thousand lacerations.", "You take a detour from the worn path, traveling for miles until you find the edges of the bush. It's taken time and a great deal of energy, but you manage to rejoin the worn path on the other side of the thornbush.", torch, "Your torch ignites and with it you burn an effortless path right through the thornbush. It goes up easily, and before long there is nothing left but ash. You continue down the worn path.");

var colossus = new Challenge("Colossus", 1, "Instinct", "Sat upon the worn path is some creature of colossal size. It seems at ease shoving enormous, petrified logs through its gnashing teeth, but becomes clearly aggitated and territorial when it sees you. If you're gentle, you might convince the beast that you aren't a threat. After, all, you're aren't one. But you do have concerns about what its meaty fist might do to your brain matter.", "Try to pass the Colossus.", "Wait for the Colossus to leave.", "Give some Brightbud to the Colossus.", "Though it feigns many charges towards you, you stand your ground. Your gentle posture and careful movements allow the creature to ease up. In passing, you are but a few feet from the towering behemoth as it stares at you quizzically with eyes as large as your head. But it continues munching on stone as you continue down the worn path on the other side.", "You approach the monster, but it can feel your fear and it grows more threatening. It feigns a charge, and then another, but the third one is followed through and you are flattened by the weight of its enormous fist. You awaken as a throbbing heap on the ground some hours later. The creature has left, and you are free to hobble onward down the worn path.", "You wait some distance from the behemoth and watch silently as it rips the trees from the earth one at a time and devours them. You lose track of how many hours pass or how many trees have vanished, but at last the giant lifts itself and moves along, shaking the earth as it goes. The weight was rather draining, but you are free to continue down the worn path.", brightbud, "You retrieve the brightbud from your belongings and its pungent aroma immediately saturates the air. The colossus perks up and fixates on it. You walk right up to the monstrous creature and it eagerly accepts the brightbud, giving you no trouble as you continue down the worn path.");

var bandits = new Challenge("Bandits", 1, "Luck", "You are stopped by a man clad in bloodied, tattered robes. He says nothing and holds up a severed head in one hand and a pouch of coins in the other. You can smell the ambush, and you might be able to talk your way out of this. If you can't, there's nobody around to help you.", "Approach the Bandit.", "Flee and find a way around them.", "Pull out a Portrait Coin.", "As you get closer to the bandit, he steps back in disbelief, dropping the head and the satchel to the floor. In awe, and stammers in a foreign tongue before he and a hidden bandit behind you flee into the woods. Perhaps they mistook you for someone more formidable, but no matter what happened you are free to continue down the worn path.", "You approach the bandit and use gestures to try to communicate. But one step closer and the bandit drops the severed head and the satchel and pulls a wicked knife from his belt. A second bandit steps out from behind you.", "Your adrenaline pumps and in a flash, you've turned and sprinted to far from the ambush for anyone to keep up. You inevitably find a trail around and rejoin the path, but you can hardly catch your breath.", portrait_coin, "You reach into your bag and pull out a large coin with the portrait of a woman on it. The bandit seems impressed by your offer. You toss the coin to the man who nods in the direction of the worn path, which you are now free to continue down.");